# Generated by Django 3.1.5 on 2021-01-26 19:39

import uuid
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='title', unique=True)),
                ('category_type', models.CharField(choices=[('blog', 'Blog'), ('resume', 'Resume'), ('flashcard', 'Flash Card'), ('exercise', 'Exercise'), ('study', 'Study'), ('modal', 'Modal')], default='flashcard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='title', unique=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_name', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('cat_sort', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('group_type', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.category')),
            ],
            options={
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, db_index=True, max_length=120)),
                ('short_title', models.CharField(blank=True, db_index=True, max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=150, populate_from='subtitle')),
                ('note', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('standalone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_path', models.CharField(blank=True, max_length=100)),
                ('image_info_key', models.CharField(default='default', max_length=20)),
                ('guid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
            ],
            options={
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='link_text', unique=True)),
                ('url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_text', models.CharField(blank=True, default='link', max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'reference',
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='ParagraphReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.paragraph')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.reference')),
            ],
        ),
        migrations.AddField(
            model_name='paragraph',
            name='references',
            field=models.ManyToManyField(through='projects.ParagraphReference', to='projects.Reference'),
        ),
        migrations.CreateModel(
            name='GroupParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.group')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.paragraph')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='paragraphs',
            field=models.ManyToManyField(through='projects.GroupParagraph', to='projects.Paragraph'),
        ),
    ]
