# Generated by Django 3.0.7 on 2020-09-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200918_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('resume', 'Resume'), ('flash_card', 'Flash Card'), ('exercise', 'Exercise')], default='flash_card', max_length=20),
        ),
    ]
