# Generated by Django 3.0.7 on 2020-10-13 16:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200925_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='link_text', unique=True),
        ),
    ]
