# Generated by Django 3.0.6 on 2020-06-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200528_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='slug',
        ),
    ]
