# Generated by Django 3.0.7 on 2020-10-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201013_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='short_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
