# Generated by Django 3.0.7 on 2020-08-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200616_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='image_info_key',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='image_path',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
