# Generated by Django 3.0.7 on 2020-10-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_group_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cat_sort',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
