# Generated by Django 3.0.7 on 2020-10-31 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_group_cat_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='short_name',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
