# Generated by Django 3.0.7 on 2020-11-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201031_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('resume', 'Resume'), ('flashcard', 'Flash Card'), ('exercise', 'Exercise')], default='flashcard', max_length=20),
        ),
    ]
