# Generated by Django 3.0.7 on 2020-08-11 19:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_paragraph_guid_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='guid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
