# Generated by Django 3.0.7 on 2020-11-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20201102_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='short_text',
            field=models.CharField(blank=True, default='link', max_length=20, null=True),
        ),
    ]
