# Generated by Django 3.0.7 on 2020-11-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20201130_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='short_text',
            field=models.CharField(blank=True, default='link', max_length=30, null=True),
        ),
    ]
