# Generated by Django 3.1.4 on 2020-12-16 15:34

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20201130_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=150, populate_from='subtitle'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('resume', 'Resume'), ('flashcard', 'Flash Card'), ('exercise', 'Exercise'), ('study', 'Study'), ('modal', 'Modal')], default='flashcard', max_length=20),
        ),
    ]
