# Generated by Django 3.0.7 on 2020-08-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_category'),
    ]

    operations = [
        migrations.RunSQL('''ALTER TABLE projects_group ADD COLUMN category_id INTEGER;
                             ALTER TABLE projects_group
                             ADD CONSTRAINT fk_category_id
                             FOREIGN KEY (category_id)
                             REFERENCES projects_category(id);'''
                          )
    ]
