# Generated by Django 3.1.4 on 2020-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20201216_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='short_title',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
